#include "ProjectExporter.h"
#include <DMGameEngine/DMGameEngine.h>
#include <DMGameEngine/Core/Log.h>
#include <filesystem>
#include <fstream>
#include <unordered_set>
#include <set>

namespace ProjectExporter {

namespace {

namespace fs = std::filesystem;

using DMGameEngine::AssetManager;
using DMGameEngine::Entity;
using DMGameEngine::MeshComponent;

// Same source the editor reads shaders/models from (see EditorLayer.cpp /
// EditorScene.cpp hard-coded asset roots - the editor has no config for it).
constexpr const char* kEngineShaderDir = "D:/CPPPractices/DMGameEngine/engine/shaders";

void WriteTextFile(const fs::path& path, const std::string& content) {
    std::ofstream out(path, std::ios::binary);
    out << content;
}

std::string GeneratedCMakeLists() {
    return R"CMAKE(cmake_minimum_required(VERSION 3.20)
project(ExportedGame LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# ── Path to the DMGameEngine source tree ──────────────────────────
# Point this at the <repo>/engine directory (the one containing
# CMakeLists.txt and dependencies/). The engine does not yet install a
# find_package()-able package (no Config file; its install(EXPORT) cannot
# be generated because of the un-exportable PUBLIC glm/entt links), so
# this template consumes the engine by source. See README.md.
set(DMGE_ENGINE_DIR "" CACHE PATH "DMGameEngine source directory (the engine/ folder)")
if(NOT EXISTS "${DMGE_ENGINE_DIR}/CMakeLists.txt")
    message(FATAL_ERROR
        "DMGE_ENGINE_DIR is not set to a DMGameEngine source tree. "
        "Configure with: cmake -B build -DDMGE_ENGINE_DIR=\"<path to DMGameEngine/engine>\"")
endif()

# The exported game does not need the engine's unit tests / FetchContent deps.
set(DMGE_BUILD_TESTS OFF CACHE BOOL "" FORCE)

add_subdirectory("${DMGE_ENGINE_DIR}" "DMGameEngine-build")

add_executable(ExportedGame src/main.cpp)
target_link_libraries(ExportedGame PRIVATE DMGameEngine)
# ImGui: single context lives in the engine DLL - import its symbols (R7).
target_compile_definitions(ExportedGame PRIVATE "IMGUI_API=__declspec(dllimport)")
target_include_directories(ExportedGame PRIVATE
    "${DMGE_ENGINE_DIR}/dependencies/imgui"
    "${DMGE_ENGINE_DIR}/dependencies/imgui/backends")
if(MSVC)
    target_compile_options(ExportedGame PRIVATE /W4 /utf-8)
endif()

add_custom_command(TARGET ExportedGame POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_if_different
        $<TARGET_FILE:DMGameEngine> $<TARGET_FILE_DIR:ExportedGame>
    COMMENT "Copying DMGameEngine.dll next to the game exe")
)CMAKE";
}

std::string GeneratedMainCpp() {
    return R"CPP(// Generated by DMGameEditor - "Export Runnable Project".
// A minimal DMGameEngine consumer: loads a .scene file and runs the scene
// systems (Transform/Light/MeshRender) in a window, editor-camera style.
#include <DMGameEngine/DMGameEngine.h>
#include <DMGameEngine/Core/EntryPoint.h>

#include <filesystem>
#include <memory>
#include <string>

// The engine's EntryPoint.h provides main() without exposing argv, so the
// scene path is read from the CRT globals (MSVC). Usage:
//   ExportedGame.exe [path/to/scene.scene]
static std::string ResolveScenePath() {
    for (int i = 1; i < __argc; ++i) {
        std::string arg = __argv[i];
        if (!arg.empty() && arg[0] != '-')
            return arg;
    }
    return "assets/scene/main.scene";
}

class RuntimeSceneLayer : public DMGameEngine::DefaultSceneLayer {
public:
    explicit RuntimeSceneLayer(std::string scenePath)
        : DefaultSceneLayer("RuntimeScene"), m_ScenePath(std::move(scenePath)) {}

    void OnAttach() override {
        using namespace DMGameEngine;
        DMGE_CLIENT_INFO("RuntimeSceneLayer: loading '{}'", m_ScenePath);

        RenderCommand::SetClearColor({0.10f, 0.10f, 0.12f, 1.0f});
        RenderCommand::SetDepthTest(true);
        RenderCommand::SetDepthFunc(DepthFunc::Less);
        RenderCommand::SetCullMode(CullMode::Back);

        m_Scene = DM::CreateRef<Scene>();
        m_Scene->AddSystem(DM::CreateRef<TransformSystem>(*m_Scene));
        m_Scene->AddSystem(DM::CreateRef<LightSystem>(*m_Scene));
        m_Scene->AddSystem(DM::CreateRef<MeshRenderSystem>(*m_Scene));

        auto cam = DM::CreateRef<EditorCameraController>(45.0f, 16.0f / 9.0f, 0.1f, 1000.0f);
        cam->SetDistance(8.0f);
        SetCameraController(cam);

        // Registry snapshot exported by the editor (UUID -> original path).
        // Only used as metadata; meshes are actually re-bound from the files
        // copied under assets/models/ (see RepairMeshesAndMaterials).
        AssetManager::Get().LoadRegistry("assets/registry.json");

        if (!SceneSerializer::Load(*m_Scene, m_ScenePath))
            DMGE_CLIENT_ERROR("Failed to load scene '{}'", m_ScenePath);

        RepairMeshesAndMaterials();
    }

private:
    // The editor assigns default materials at runtime and procedural meshes
    // (never registered with the AssetManager) cannot survive serialization.
    // Re-bind meshes from the exported copies and give anything without a
    // material the same default the editor used.
    void RepairMeshesAndMaterials() {
        using namespace DMGameEngine;
        auto shader = AssetManager::Get().Load<Shader>("shaders/BlinnPhong.glsl");
        DM::Ref<Material> baseMat;
        if (shader) {
            baseMat = DM::CreateRef<Material>(shader);
            baseMat->SetFloat3("u_AlbedoColor", {0.8f, 0.8f, 0.85f});
            baseMat->SetFloat("u_SpecularStrength", 0.5f);
            baseMat->SetFloat("u_Shininess", 64.0f);
            baseMat->SetInt("u_UseTexture", 0);
        } else {
            DMGE_CLIENT_ERROR("Failed to load shaders/BlinnPhong.glsl - run the exe from the project root");
        }

        auto& reg = m_Scene->GetRegistry();
        reg.view<MeshComponent>().each([&](auto eh, MeshComponent& mc) {
            (void)eh;
            if (!mc.Mesh && mc.MeshAsset.IsValid()) {
                if (const auto* meta = AssetManager::Get().GetMetadata(mc.MeshAsset.GetUUID())) {
                    std::filesystem::path local =
                        std::filesystem::path("assets/models") /
                        std::filesystem::path(meta->Path).filename();
                    if (std::filesystem::exists(local))
                        mc.Mesh = AssetManager::Get().Load<Mesh>(local.string());
                }
            }
            if (mc.Mesh && mc.MaterialOverrides.empty() && baseMat) {
                mc.MaterialOverrides.resize(mc.Mesh->SubMeshes.size());
                for (auto& ov : mc.MaterialOverrides)
                    ov = DM::CreateRef<MaterialInstance>(baseMat);
            }
            if (!mc.Mesh)
                DMGE_CLIENT_WARN("An entity mesh could not be resolved (procedural or missing asset file)");
        });
    }

    std::string m_ScenePath;
};

class ExportedGame : public DMGameEngine::Application {
public:
    ExportedGame()
        : Application(DMGameEngine::WindowProps("DMGameEngine - Exported Game", 1280, 720)) {}

    void OnInitialize() override {
        DMGE_CLIENT_INFO("Exported game initialized");
        GetWindow().SetVSync(true);
        PushLayer(std::make_unique<RuntimeSceneLayer>(ResolveScenePath()));
    }

    void OnEvent(DMGameEngine::Event& e) override {
        DMGameEngine::EventDispatcher dispatcher(e);
        dispatcher.Dispatch<DMGameEngine::KeyPressedEvent>(
            [](DMGameEngine::KeyPressedEvent& key) {
                if (key.GetKeyCode() == DMGameEngine::KeyCode::Escape) {
                    DMGE_CLIENT_INFO("Escape pressed - quitting");
                    DMGameEngine::Application::Get().Quit();
                    return true;
                }
                return false;
            });
        Application::OnEvent(e);
    }

    void OnShutdown() override { DMGE_CLIENT_INFO("Exported game shutting down"); }
};

DMGameEngine::Application* DMGameEngine::CreateApplication() {
    DMGameEngine::Renderer::SetAPI(DMGameEngine::Renderer::API::OpenGL);
    return new ExportedGame();
}
)CPP";
}

std::string GeneratedReadme(const std::string& sceneFile) {
    return R"README(# Exported DMGameEngine Project

Generated by DMGameEditor ("File > Export Runnable Project...").

## Build

    cmake -B build -DDMGE_ENGINE_DIR="<path to DMGameEngine>/engine"
    cmake --build build

(Any generator works; on Windows/MSVC open the folder in an environment
where cl.exe is available, e.g. a VS developer shell or CLion.)

## Run

Run from THIS directory (shader/asset paths are relative to the CWD):

    build\ExportedGame.exe

This loads `)README" + sceneFile + R"README(`. Optionally pass another scene:
`build\ExportedGame.exe <path-to-.scene>`.

## Notes

- The scene was serialized with the editor's asset UUID registry
  (`assets/registry.json`); referenced model files were copied to
  `assets/models/` and re-bound at startup by the generated `src/main.cpp`.
- Procedural (in-editor generated) meshes cannot be serialized - if the
  editor warned about them during export, those entities will log a warning
  and render nothing here. Replace them with imported model assets.
- The engine is built from source via `DMGE_ENGINE_DIR`: the engine's
  install/export rules do not yet produce a `find_package`-able package.
)README";
}

bool CopyDirectoryTree(const fs::path& src, const fs::path& dst, std::string& error) {
    std::error_code ec;
    if (!fs::exists(src, ec)) {
        error = "source directory missing: " + src.string();
        return false;
    }
    fs::create_directories(dst, ec);
    for (auto& it : fs::recursive_directory_iterator(src, ec)) {
        if (ec) break;
        const auto rel = fs::relative(it.path(), src, ec);
        const auto target = dst / rel;
        if (it.is_directory(ec)) {
            fs::create_directories(target, ec);
        } else if (it.is_regular_file(ec)) {
            fs::create_directories(target.parent_path(), ec);
            fs::copy_file(it.path(), target, fs::copy_options::overwrite_existing, ec);
            if (ec) { error = "copy failed: " + it.path().string(); return false; }
        }
    }
    return true;
}

} // namespace

ExportResult Export(const std::string& outputDir, const DMGameEngine::Scene& editScene) {
    ExportResult result;
    namespace fs = std::filesystem;
    std::error_code ec;

    const fs::path out = fs::path(outputDir).lexically_normal();
    if (out.empty()) { result.Error = "empty output directory"; return result; }

    fs::create_directories(out / "assets/scene", ec);
    fs::create_directories(out / "assets/models", ec);
    fs::create_directories(out / "src", ec);
    if (ec) { result.Error = "cannot create output directories: " + ec.message(); return result; }

    // 1. Scene dump (always the EDIT state; the caller guarantees it).
    const std::string sceneRel = "assets/scene/main.scene";
    DMGameEngine::SceneSerializer::Save(editScene, (out / sceneRel).string());

    // 2. Asset registry snapshot (UUID -> original path metadata; used by the
    // generated main.cpp to re-bind copied model files by UUID).
    AssetManager::Get().SaveRegistry((out / "assets/registry.json").string());

    // 3. Copy model files referenced by the scene (UUID -> path via AssetManager).
    std::unordered_set<DMGameEngine::AssetUUID> copied;
    std::set<std::string> copiedFilenames;
    editScene.GetRegistry().view<MeshComponent>().each([&](auto, const MeshComponent& mc) {
        if (!mc.MeshAsset.IsValid()) {
            if (mc.Mesh)
                result.ProceduralMeshes++;   // K-012: procedural meshes do not survive serialization
            return;
        }
        if (copied.count(mc.MeshAsset.GetUUID()))
            return;
        const auto* meta = AssetManager::Get().GetMetadata(mc.MeshAsset.GetUUID());
        if (!meta || meta->Path.empty())
            return;
        const fs::path srcPath = meta->Path;
        if (!fs::exists(srcPath, ec))
            return;   // dangling registry entry; runtime will warn
        fs::path dst = out / "assets/models" / srcPath.filename();
        if (!copiedFilenames.insert(srcPath.filename().string()).second)
            return;   // same filename from a different directory: first one wins, runtime dedupes by path
        fs::copy_file(srcPath, dst, fs::copy_options::overwrite_existing, ec);
        if (ec) {
            DMGE_CLIENT_WARN("Export: failed to copy model '{0}': {1}", srcPath.string(), ec.message());
            ec.clear();
            return;
        }
        copied.insert(mc.MeshAsset.GetUUID());
        result.ModelsCopied++;
    });

    // 4. Engine shaders -> <out>/shaders (relative shader paths in the game).
    std::string err;
    if (!CopyDirectoryTree(kEngineShaderDir, out / "shaders", err)) {
        result.Error = "shader copy failed: " + err;
        return result;
    }

    // 5. Project template.
    WriteTextFile(out / "CMakeLists.txt", GeneratedCMakeLists());
    WriteTextFile(out / "src" / "main.cpp", GeneratedMainCpp());
    WriteTextFile(out / "README.md", GeneratedReadme(sceneRel));

    result.OutputDir = out.string();
    result.Ok = true;
    return result;
}

} // namespace ProjectExporter
